function CODE_Figure(X1, YMatrix1,yLBL)%, YMatrix2, YMatrix3, YMatrix4)
global d BETA
Np=10;
%CREATEFIGURE(X1,YMATRIX1,YMATRIX2,YMATRIX3,YMATRIX4)
%  Auto-generated by MATLAB on 06-May-2014 22:04:54
% Create figure
figure1 = figure('PaperType','<custom>','PaperSize',[53.25 75.33],...
    'PaperUnits','centimeters');

% Create axes
axes('Parent',figure1,'ZColor',[1 1 1],'YTickLabel','','YTick',zeros(1,0),...
    'YColor',[1 1 1],...
    'XTickLabel','',...
    'XTick',zeros(1,0),...
    'XColor',[1 1 1],...
    'Position',[0.05405 0.05368 0.9346 0.8975],...
    'CLim',[0 1]);

% Create title
title('Crosspatch Infestation in Mesh Arrangement Model',...
    'FontSize',20,...
    'Editing','on');
xlabel('Time (in years)','FontSize',16,'Color',[0 0 0]);
% Create xlabel TO BE CORRECTED
% if strcmp(xLBL,'Social norms')
% xlabel('Social norms n','FontSize',16,'Color',[0 0 0]);
% elseif strcmp(xLBL,'Infested')
% xlabel('Number of Infested trees','FontSize',16,'Color',[0 0 0]);
% elseif strcmp(xLBL,'Strategists')
% xlabel('Number of Local Strategists','FontSize',16,'Color',[0 0 0]);
% elseif strcmp(xLBL,'Crosspatch infestation')
% xlabel('Crosspatch Infestation','FontSize',16,'Color',[0 0 0]);
% elseif strcmp(xLBL,'Time to Crosspatch')
% xlabel('Time to Crosspatch Infestation','FontSize',16,'Color',[0 0 0]);
% end

% Create ylabel
if strcmp(yLBL,'Susceptible')
ylabel('Number of Susceptible trees','FontSize',16,'Color',[0 0 0]);
elseif strcmp(yLBL,'Infested')
ylabel('Number of Infested trees','FontSize',16,'Color',[0 0 0]);
elseif strcmp(yLBL,'Strategists')
ylabel('Number of Local Strategists','FontSize',16,'Color',[0 0 0]);
elseif strcmp(yLBL,'Crosspatch infestation')
ylabel('Crosspatch Infestation','FontSize',16,'Color',[0 0 0]);
elseif strcmp(yLBL,'Time to Crosspatch')
ylabel('Time to Crosspatch Infestation','FontSize',16,'Color',[0 0 0]);
end
% Create axes
axes1 = axes('Parent',figure1,'FontSize',14,'Position',[0.13 0.09878 0.8323 0.8009]);
grid(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
for i=1:Np
    set(plot1(i),'DisplayName',['Patch ' int2str(i)],'Color',[1/i i/Np 1/(Np-i+1)]);
end

legend1 = legend(axes1,'show');
set(legend1,'Position',[0.1413 0.5674 0.1355 0.1298]);